import type {Metadata} from 'next';
import {NextIntlClientProvider} from 'next-intl';
import {getMessages, getTranslations} from 'next-intl/server';
// import {SessionProvider} from 'next-auth/react';
import {ReduxProvider} from '@/lib/providers/reduxProvider';
import {Geist, Geist_Mono} from 'next/font/google';
import { Layout } from '@/components/layout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  const {locale} = await Promise.resolve(params);
  const messages = await getMessages();

  return (
    // Providers for the [locale] subtree. Root <html> and <body> are defined in app/layout.tsx
    // <SessionProvider>
    // <ReduxProvider>
      <NextIntlClientProvider messages={messages}>
        <div suppressHydrationWarning>
          <Layout>{children}</Layout>
        </div>
      </NextIntlClientProvider>
    // </ReduxProvider>
    // </SessionProvider>
  );
}
